accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
]

book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ListBookView.as_view(), name='list-book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name='detail-book'),
    path('book/create/', views.CreateBookView.as_view(), name='create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name='update-book'),
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name='review'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('book.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models
from .consts import MAX_RATE

RATE_CHOICES = [(x, str(x)) for x in range(0, MAX_RATE + 1)]

CATEGORY = (
    ('business', 'ビジネス'),
    ('life', '生活'),
    ('hobby', '趣味'),
    ('other', 'その他'),
)

class Shelf(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    thumbnail = models.ImageField(null=True, blank=True)
    category = models.CharField(
        max_length=100,
        choices = CATEGORY,
        )
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Review(models.Model):
    book = models.ForeignKey(Shelf, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignupView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

book/views.py
from django.shortcuts import reverse,render
from django.views import generic
from django.urls import reverse, reverse_lazy
from .models import Shelf, Review
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.core.paginator import Paginator

class ListBookView(generic.ListView):
    template_name = 'book/book_list.html'
    model = Shelf
    context_object_name = 'Shelf'
    queryset = Shelf.objects.all().order_by('-id')  # 登録順（降順）に並べ替え
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # レビュー平均でソートして上位3冊を取得
        ranking_list = (
            Shelf.objects.annotate(avg_rating=Avg('review__rate')).order_by('-avg_rating')[:3]
        )
        context['ranking_list'] = ranking_list
        return context
class DetailBookView(generic.DetailView):
    template_name = 'book/book_detail.html'
    model = Shelf
    context_object_name = 'Shelf'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 本に関連するレビューを取得
        reviews = Review.objects.filter(book=self.object).order_by('-id')  # 最新のレビュー順
        paginator = Paginator(reviews, 3)  # 1ページに3件表示
        page_number = self.request.GET.get('page')
        context['reviews'] = paginator.get_page(page_number)
        return context
class CreateBookView(LoginRequiredMixin,generic.CreateView):
    template_name = 'book/book_create.html'
    model = Shelf
    context_object_name = 'Shelf'
    fields = ('title', 'text', 'category', 'thumbnail')
    success_url = reverse_lazy('list-book')
    def form_valid(self, form):
        form.instance.user = self.request.user  # ログイン中のユーザーを設定
        return super().form_valid(form)

class DeleteBookView(LoginRequiredMixin,generic.DeleteView):
    template_name = 'book/book_confirm_delete.html'
    model = Shelf
    context_object_name = 'Shelf'
    success_url = reverse_lazy('list-book')
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            raise PermissionDenied('削除権限がありません。')
        return super(DeleteBookView, self).dispatch(request, *args, **kwargs)
    
class UpdateBookView(LoginRequiredMixin,generic.UpdateView):
    template_name = 'book/book_update.html'
    model = Shelf
    context_object_name = 'Shelf'
    fields = ('title', 'text', 'category','thumbnail')
    success_url = reverse_lazy('list-book')
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            raise PermissionDenied('編集権限がありません。')
        return super(UpdateBookView, self).dispatch(request, *args, **kwargs)
    
class CreateReviewView(LoginRequiredMixin,generic.CreateView):
    model = Review
    fields = ('book', 'title', 'text', 'rate')
    template_name = 'book/review_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Shelf.objects.get(pk=self.kwargs['book_id'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail-book', kwargs={'pk':self.object.book.id})

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}アカウント作成{% endblock %}

{% block h1 %}アカウント作成{% endblock %}

{% block content %}
<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <input type="text" name="username" class="form-control my-4" placeholder="ユーザID" required="required">
    <input type="password" name="password1" class="form-control mt-4" placeholder="パスワード" required="required">
    <input type="password" name="password2" class="form-control mt-4" placeholder="パスワード確認用" required="required">
    <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください。</small>
    {% if form.errors %}
    <div class="alert alert-danger">
        {% for error_list in form.errors.values %}
        {% for error in error_list %}
        <p class="mb-0">{{ error }}</p>
        {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} Bootstrap CSS {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %} | 本棚アプリ</title>
    <style>
        body {
            font-family: "Dela Gothic One", serif;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-dark bg-success sticky-top">
        <div class="navbar-nav d-flex flex-row">
            <a href="{% url 'list-book' %}" class="nav-link mx-3">書籍一覧</a>
            {% if user.is_authenticated %}
            <a href="{% url 'create-book' %}" class="nav-link mx-3">書籍登録</a>
            {% endif %}
        </div>
        <div class="navbar-nav d-flex flex-row">
            {% if user.is_authenticated %}
            <span class="navbar-text mx-3">{{ user }}でログイン中</span>
            <a href="{% url 'logout' %}" class="nav-link mx-3">ログアウト</a>
            {% else %}
            <a href="{% url 'login' %}" class="nav-link mx-3">ログイン</a>
            <a href="{% url 'accounts:signup' %}" class="nav-link mx-3">会員登録</a>
            {% endif %}
        </div>
    </nav>
    <div class="p-4">
        <h1>{% block h1 %}{% endblock %}</h1>
        {% block content %}{% endblock %}
    </div>

</body>

</html>

templates/book/book_confirm_delete.html
{% extends "base.html" %}

{% block title %}書籍削除{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <button type="submit">{{ Shelf.title }}を削除する</button>
</form>
{% endblock %}

templates/book/book_create.html
{% extends "base.html" %}

{% block title %}書籍作成{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">作成する</button>
</form>
{% endblock %}

templates/book/book_detail.html
{% extends "base.html" %}

{% block title %}{{ Shelf.title }}{% endblock %}
{% block h1 %}書籍詳細{% endblock %}

{% block content %}
<div class="p-4 m-4 bh-light border border-success rounded">
    <h2 class="text-success">{{ Shelf.title }}</h2>
    <p>{{ Shelf.text }}</p>
    {% if user.is_authenticated %}
    <a href="{% url 'review' Shelf.pk %}" class="btn btn-outline-success btn-sm mb-3">レビューを書く</a>
    {% endif %}
    <h6 class="card-title mb-3 fw-light">カテゴリ：{{ Shelf.category }}</h6>
    <div class="border p-4 mb-2">
        <h3>レビュー</h3>
        {% if reviews %}
        <ul>
            {% for review in reviews %}
            <li>
                <strong>{{ review.title }}</strong>
                (評価:{{ review.rate }})
                <p>{{ review.text }}</p>
                <p>投稿者:{{ review.user.username }}</p>
            </li>
            {% endfor %}
        </ul>

        <!-- ページネーションのナビゲーションaaa -->
        <div class="pagination">
            <span>
                {% if reviews.has_previous %}
                <a href="?page={{ reviews.previous_page_number }}"
                    class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"><small>&lt;&lt;前へ</small></a>
                {% endif %}
            </span>
            <span class="mx-3">{{ reviews.number }}ページ目</span>
            <span>
                {% if reviews.has_next %}
                <a href="?page={{ reviews.next_page_number }}"
                    class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"><small>次へ&gt;&gt;</small></a>
                {% endif %}
            </span>
        </div>
        {% else %}
        <p>レビューはまだありません。</p>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'update-book' Shelf.pk %}" class="btn btn-outline-primary btn-sm">編集する</a>
    <a href="{% url 'delete-book' Shelf.pk %}" class="btn btn-outline-danger btn-sm">削除する</a>
    {% endif %}
    <p class="mt-3">
        <a href="{% url 'list-book' %}"
            class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">一覧へ戻る</a>
    </p>
</div>
{% endblock %}

templates/book/book_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    {% comment %} 登録順 {% endcomment %}
    <div class="col-md-9">
        {% for item in Shelf %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-sccess">{{ item.title }}</h2>
            {% if item.thumbnail %}
            <div class="w-25 p-3">
                <img src="{{ item.thumbnail.url }}" class="img-thumbnail">
            </div>
            {% else %}
            <p>No thumbnail available</p>
            {% endif %}
            <h6 class="fw-light">カテゴリ：{{ item.category }}</h6>
            <div class="mt-3">
                <a href="{% url 'detail-book' item.pk %}"
                    class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">詳細へ</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% comment %} レビュー順 {% endcomment %}
    <div class="col-md-3">
        <h2>レビュー好評　TOP3</h2>
        {% for ranking_book in ranking_list %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h3 class="text-success h5">{{ ranking_book.title }}</h3>
            <div class="w-80 p-3">
                <img src="{{ ranking_book.thumbnail.url }}" class="img-thumbnail">
            </div>
            <h6>評価：{{ ranking_book.avg_rating|floatformat:2 }}点</h6>
            <a href="{% url 'detail-book' ranking_book.id %}"
                class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">詳細へ</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/book/book_update.html
{% extends "base.html" %}

{% block title %}書籍修正{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">修正する</button>
</form>
{% endblock %}

templates/book/review_form.html
{% extends "base.html" %}

{% block title %}レビュー投稿{% endblock %}

{% block h1 %}レビュー投稿{% endblock %}

{% block content %}
<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <label>対象書籍</label>
    <input class="form-control" value="{{ book.title }}" readonly>
    <label>タイトル</label>
    <input type="text" class="form-control" name="title">
    <label>本文</label>
    <textarea class="form-control" name="text" rows="3"></textarea>
    <label>星の数</label>
    <select class="form-control" name="rate">
        <option value="0">0（最低）</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3" selected>3</option>
        <option value="4">4</option>
        <option value="5">5（最高）</option>
    </select>
    <input type="hidden" name="book" value="{{ book.id }}">
    <button type="submit" class="btn btn-success mt-4">投稿する</button>
</form>
{% endblock %}